echo -e "\E(0l\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0k\E(B"
echo -e "\E(0x\E(B \E(0a\E(B\E(0a\E(B\E(0a\E(B\E(0a\E(B\E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B   \E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B   \E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B   \E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B   \E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B   \E(0a\E(B \E(0x\E(B"
echo -e "\E(0x\E(B \E(0a\E(B\E(0a\E(B\E(0a\E(B\E(0a\E(B\E(0a\E(B \E(0x\E(B"
echo -e "\E(0m\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0q\E(B\E(0j\E(B"